language: c
script:
  - cmake . -DCMAKE_BUILD_TYPE=$CONFIG
  - cmake --build . --config %CONFIG%
  - python scripts/build_tests.py
  - python scripts/tester.py -vv --exe ./binjgb-tester

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
      env: CONFIG=Release
    - os: linux
      dist: trusty
      sudo: false
      compiler: clang
      env: CONFIG=Debug
    - os: linux
      dist: trusty
      sudo: false
      compiler: clang
      env: CONFIG=Release
    - os: osx
      compiler: clang
      env: CONFIG=Release

  allow_failures:
    - os: osx

  fast_finish: true
