environment:
  matrix:
    - GENERATOR: Visual Studio 14 2015
      CONFIG: Release
    - GENERATOR: Visual Studio 14 2015 Win64
      CONFIG: Debug
    - GENERATOR: Visual Studio 14 2015 Win64
      CONFIG: Release

build_script:
  - cmake . -DCMAKE_BUILD_TYPE=%CONFIG% -G %GENERATOR%
  - cmake --build . --config %CONFIG%
