install:
  - git submodule update --init

environment:
  SDL2_ZIP: SDL2-devel-2.0.5-VC.zip
  SDL2_DOWNLOAD_DIR: c:\sdl2
  SDL2_ROOT_DIR: c:\sdl2\SDL2-2.0.5
  matrix:
    - GENERATOR: Visual Studio 14 2015
      CONFIG: Release
    - GENERATOR: Visual Studio 14 2015 Win64
      CONFIG: Debug
    - GENERATOR: Visual Studio 14 2015 Win64
      CONFIG: Release

build_script:
  - cmake --version
  - mkdir %SDL2_DOWNLOAD_DIR%
  - cd %SDL2_DOWNLOAD_DIR%
  - appveyor DownloadFile https://www.libsdl.org/release/%SDL2_ZIP%
  - 7z x %SDL2_ZIP% > nul
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake .  -G "%GENERATOR%" -DSDL2_ROOT_DIR=%SDL2_ROOT_DIR% -DCMAKE_BUILD_TYPE=%CONFIG%
  - cmake --build . --config %CONFIG%
